name: CoCoolEvents
version: '1.8'
main: ir.compe.thefly.TheFly
api-version: '1.20'
commands:
  CoCoolEvents:
    description: Plugin Info
    aliases:
      - co
      - cool
      - cocool
      - cc
      - Events
      - salam
      - fuck
